src/Synapse/Page/Bundle/Form/PageMenu/PageMenuType.php
<?php

namespace Synapse\Page\Bundle\Form\PageMenu;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Synapse\Cmf\Bundle\Form\Type\Theme\ComponentDataType;
use Synapse\Page\Bundle\Form\PageMenu\DataMapper\PageMenuTreeMapper;

/**
 * PageMenu component form type.
 */
class PageMenuType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return ComponentDataType::class;
    }

    /**
     * Menu component form prototype definition.
     *
     * @see FormInterface::buildForm()
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('menu_tree', CollectionType::class, array(
                'entry_type' => PageMenuItemType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'delete_empty' => true,
                'attr' => [
                    'class' => 'synapse-page-menu-data',
                ], ))
            ->setDataMapper(new PageMenuTreeMapper('menu_tree'))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['attr'] = array(
            'class' => 'synapse-page-menu-component',
        );
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'page_menu';
    }
}

src/Synapse/Page/Bundle/Resources/views/Admin/Page/create.html.twig
{% extends 'SynapsePageBundle::layout.html.twig' %}

{% form_theme form 'SynapseAdminBundle:Form:synapse_admin_form_layout.html.twig' %}

{% block content %}
  {{ form_start(form) }}

  <div class="row-fluid">
    <div class="col-fill">
      <div class="panel">
        <header class="panel-heading composed bg-main">
          <a href class="combo">
            <i class="fa fa-file-text-o"></i>
          </a>
          <h3>New page</h3>
        </header>
        <div class="panel-body">
          {{ form_row(form.name) }}
          {{ form_row(form.parent) }}
          {{ form_row(form.title) }}
          {{ form_row(form.path) }}
        </div>
      </div>
    </div>
    <div class="col-fix">
      <div class="button-bar" data-spy="affix" data-offset-top="55">
        <a class="btn btn-big btn-warning" href="{{ path('synapse_admin_page_list') }}">
          <i class="fa fa-times"></i>
          <span>Cancel</span>
        </a>
        {% set void = form.submit.setRendered(true) %}
        <button class="btn btn-big btn-success" type="submit"
          id="{{ form.submit.vars.id }}" name="{{ form.submit.vars.full_name }}"
        >
          <i class="fa fa-2x fa-check"></i>
          Submit
        </button>
      </div>
    </div>
  {{ form_end(form) }}
{% endblock %}

src/Synapse/Page/Bundle/Resources/views/Admin/Page/edit.html.twig
{% extends 'SynapsePageBundle::layout.html.twig' %}

{% form_theme form 'SynapseAdminBundle:Form:synapse_admin_form_layout.html.twig' %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <ul class="breadcrumb">
        <li>
          <a href="{{ path('synapse_admin_page_list') }}">
            <i class="fa fa-files-o"></i>
            Pages
          </a>
        </li>
        <li class="active">{{ page.name }}</li>
        <li class="active">edit</li>
      </ul>
    </div>
  </div>

  {{ form_start(form) }}

  <div class="row-fluid">
    <div class="col-fill row">

      {# General #}
      <div id="form-general" class="panel col-md-6">
        <header class="panel-heading composed bg-main">
          <a href class="combo">
            <i class="fa fa-file-text-o"></i>
          </a>
          <h3>General</h3>
        </header>
        <div class="panel-body">
          {{ form_row(form.name) }}
          {{ form_row(form.online) }}
        </div>
      </div>

      {# Metas #}
      <div id="form-meta" class="panel col-md-6">
        <header class="panel-heading composed bg-main">
          <a href class="combo">
            <i class="fa fa-sitemap"></i>
          </a>
          <h3>Metadata</h3>
        </header>
        <div class="panel-body">
          {{ form_row(form.meta) }}
        </div>
      </div>

      {# Content #}
      <div id="form-content" class="synapse-theme-form panel col-md-12">
        <header class="panel-heading composed bg-main">
          <a href class="combo">
            <i class="fa fa-scribd"></i>
          </a>
          <h3>Content</h3>
        </header>
        {% if form.synapse is defined %}
          {{ form_widget(form.synapse) }}
        {% else %}
          <div class="panel-body panel-body-info">
            <p class="info">
              <span class="badge label-warning"><i class="fa fa-warning"></i></span>
              You don't have any active theme, you won't be able to display the page. Create a theme and at least a template to apply one to this content.
            </p>
          </div>
        {% endif %}
      </div>

    </div>
    <div class="col-fix">
      <div class="button-bar" data-spy="affix" data-offset-top="55">
        <a class="btn btn-big btn-warning" href="{{ path('synapse_admin_page_list') }}">
          <i class="fa fa-times"></i>
          <span>Cancel</span>
        </a>
        {% set void = form.submit.setRendered(true) %}
        <button class="btn btn-big btn-success" type="submit"
          id="{{ form.submit.vars.id }}" name="{{ form.submit.vars.full_name }}"
        >
          <i class="fa fa-2x fa-check"></i>
          Submit
        </button>
      </div>
    </div>
  </div>
  {{ form_end(form) }}
{% endblock %}

src/Synapse/Page/Bundle/Resources/views/Admin/Page/list.html.twig
{% extends 'SynapsePageBundle::layout.html.twig' %}

{% block content %}
<div class="row-fluid">
  <div class="col-fill">
    <div class="panel">
      <header class="panel-heading composed bg-main">
        <a href class="combo">
          <i class="fa fa-files-o"></i>
        </a>
        <h3>Pages</h3>
      </header>
      <table class="table table-striped table-advance table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Url</th>
            <th>Online</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        {% for page in pages %}
          <tr>
            <td>
              {% for i in range(0, page.lvl) if i > 0 %}&nbsp;|---{% endfor %}
              {{ page.name }}
            </td>
            <td>
            {% if page.online %}
              <a href="{{ url(page_rendering_route, { path: page.path }, 0) }}" target="__blank">
                /{{ page.path }}
              </a>
            {% else %}
              /{{ page.path }}
            {% endif %}
            </td>
            <td>
            {% if page.online %}
              <span class="badge label-success">
                <i class="fa fa-check"></i>
              </span>
            {% else %}
              <span class="badge label-danger">
                <i class="fa fa-times"></i>
              </span>
            {% endif %}
            </td>
            <td class="text-right">
              <a class="btn btn-success btn-sm" href="{{ path('synapse_admin_page_edition', { id: page.id }) }}">
                <i class="fa fa-edit"></i>
              </a>
              <a class="btn btn-info btn-sm" href="{{ path('synapse_admin_page_preview', { id: page.id }) }}" target="__preview">
                <i class="fa fa-search"></i>
              </a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-fix">
    <div class="button-bar" data-spy="affix" data-offset-top="55">
      <a class="btn btn-big btn-primary" href="{{ path('synapse_admin_page_creation') }}">
        <i class="fa fa-plus"></i>
        <span>Create</span>
      </a>
    </div>
  </div>
</div>
{% endblock %}